title: "Nathan Reesor"
description: "Portfolio and equity dashboard"
url: "https://nathanreesor.github.io"
baseurl: ""
og_image: "/assets/images/nr-logo.svg"
markdown: kramdown
permalink: /equitydashboard/:year/:month/:day/:title/
collections:
  posts:
    output: true
    permalink: /equitydashboard/:year/:month/:day/:title/
